### ISSUE TITLE
HTTP Connector with empty HTTP Headers field throws exception

### ISSUE THREAD

**Issue by upgradingdave** [camunda/connectors-bundle#856]
__Is your feature request related to a problem? Please describe.__

When I accept defaults (leaving the `HTTP Headers` field) blank like so: 

<img width="394" alt="Screen Shot 2023-07-08 at 11 07 32 AM" src="https://github.com/camunda/connectors-bundle/assets/939229/552fbf1d-e66d-4456-b23a-21fef4164645">

 After I deploy and run a process, when the Connector attempts the api call, it fails with the following exception: 

```
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.Map.entrySet()" because "this$0.unknownFields" is null
	at com.google.api.client.util.GenericData$EntryIterator.<init>(GenericData.java:265)
	at com.google.api.client.util.GenericData$EntrySet.iterator(GenericData.java:233)
	at com.google.api.client.http.HttpHeaders.serializeHeaders(HttpHeaders.java:905)
	at com.google.api.client.http.HttpHeaders.serializeHeaders(HttpHeaders.java:893)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:927)
	at io.camunda.connector.common.services.HTTPService.executeHttpRequest(HTTPService.java:87)
	at io.camunda.connector.common.services.HTTPService.executeHttpRequest(HTTPService.java:81)
	at io.camunda.connector.http.HttpService.getTokenFromOAuthRequest(HttpService.java:95)
	at io.camunda.connector.http.HttpService.executeRequestDirectly(HttpService.java:66)
	at io.camunda.connector.http.HttpService.executeConnectorRequest(HttpService.java:55)
	at io.camunda.connector.http.HttpJsonFunction.execute(HttpJsonFunction.java:74)
	at io.camunda.connector.runtime.core.outbound.ConnectorJobHandler.handle(ConnectorJobHandler.java:72)
	... 13 common frames omitted
```

It seems I have to manually enter an empty context into the HTTP Headers like this in order for the HTTP Connector to successfully make the request?

<img width="384" alt="Screen Shot 2023-07-08 at 11 11 16 AM" src="https://github.com/camunda/connectors-bundle/assets/939229/c8f888b6-6708-43eb-96e9-319762eb379c">

I'll attached the bpmn that I'm using to consistently reproduce in a comment. 

__Describe the solution you'd like__

It shouldn't be necessary to manually enter an empty context of `{}` into the HTTP Headers. 

__Describe alternatives you've considered__

The work around is to manually enter `{}` but this was confusing for me, and I'm sure it will confuse customers. 

__Additional context__

**Comment by upgradingdave** [comment]
Here's the bpmn file to reproduce the issue: 

```
<?xml version="1.0" encoding="UTF-8"?>
<bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" xmlns:zeebe="http://camunda.org/schema/zeebe/1.0" xmlns:modeler="http://camunda.org/schema/modeler/1.0" xmlns:camunda="http://camunda.org/schema/1.0/bpmn" id="Definitions_1" targetNamespace="http://bpmn.io/schema/bpmn" exporter="Camunda Web Modeler" exporterVersion="48d65f3" modeler:executionPlatform="Camunda Cloud" modeler:executionPlatformVersion="8.3.0" camunda:diagramRelationId="ce605a49-aa8d-4abb-b010-2b3412c80ad1">
  <bpmn:process id="Process_01oeys7" name="Microsoft APIs" isExecutable="true">
    <bpmn:extensionElements>
      <zeebe:userTaskForm id="userTaskForm_1hjkdi0">{
  "components": [
    {
      "label": "Comments",
      "type": "textarea",
      "layout": {
        "row": "Row_007zgpr",
        "columns": null
      },
      "id": "Field_14f31ou",
      "key": "field_comments"
    }
  ],
  "schemaVersion": 9,
  "exporter": {
    "name": "Camunda Web Modeler",
    "version": "48d65f3"
  },
  "type": "default",
  "id": "Form_1o3x7px",
  "executionPlatform": "Camunda Cloud",
  "executionPlatformVersion": "8.2.0"
}</zeebe:userTaskForm>
    </bpmn:extensionElements>
    <bpmn:startEvent id="StartEvent_1" name="Start">
      <bpmn:outgoing>Flow_0pt0f73</bpmn:outgoing>
    </bpmn:startEvent>
    <bpmn:sequenceFlow id="Flow_0pt0f73" sourceRef="StartEvent_1" targetRef="Gateway_1728wpj" />
    <bpmn:endEvent id="Event_1nq7pa3" name="End">
      <bpmn:incoming>Flow_16iax1n</bpmn:incoming>
    </bpmn:endEvent>
    <bpmn:sequenceFlow id="Flow_1u5knz4" sourceRef="Activity_0xr2bie" targetRef="Gateway_00g9ib4" />
    <bpmn:sequenceFlow id="Flow_0644q48" sourceRef="Activity_14w6jo5" targetRef="Activity_0xr2bie" />
    <bpmn:serviceTask id="Activity_14w6jo5" name="Tasklist Rest API" zeebe:modelerTemplate="3df64d65-6cb4-46e4-bd21-dd4dea68ecde" zeebe:modelerTemplateVersion="1688826321062" zeebe:modelerTemplateIcon="data:image/svg+xml;utf8,%3Csvg%20width%3D%2218%22%20height%3D%2218%22%20viewBox%3D%220%200%2018%2018%22%20fill%3D%22none%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%0A%3Cpath%20d%3D%22M17.0335%208.99997C17.0335%2013.4475%2013.4281%2017.0529%208.98065%2017.0529C4.53316%2017.0529%200.927765%2013.4475%200.927765%208.99997C0.927765%204.55248%204.53316%200.947083%208.98065%200.947083C13.4281%200.947083%2017.0335%204.55248%2017.0335%208.99997Z%22%20fill%3D%22%23505562%22%2F%3E%0A%3Cpath%20d%3D%22M4.93126%2014.1571L6.78106%203.71471H10.1375C11.1917%203.71471%2011.9824%203.98323%2012.5095%204.52027C13.0465%205.04736%2013.315%205.73358%2013.315%206.57892C13.315%207.44414%2013.0714%208.15522%2012.5841%208.71215C12.1067%209.25913%2011.4553%209.63705%2010.6298%209.8459L12.0619%2014.1571H10.3315L9.03364%2010.0249H7.24351L6.51254%2014.1571H4.93126ZM7.49711%208.59281H9.24248C9.99832%208.59281%2010.5901%208.42374%2011.0177%208.08561C11.4553%207.73753%2011.6741%207.26513%2011.6741%206.66842C11.6741%206.19106%2011.5249%205.81811%2011.2265%205.54959C10.9282%205.27113%2010.4558%205.1319%209.80936%205.1319H8.10874L7.49711%208.59281Z%22%20fill%3D%22white%22%2F%3E%0A%3C%2Fsvg%3E%0A">
      <bpmn:extensionElements>
        <zeebe:taskDefinition type="io.camunda:custom-http-json:1" />
        <zeebe:ioMapping>
          <zeebe:input source="oauth-client-credentials-flow" target="authentication.type" />
          <zeebe:input source="get" target="method" />
          <zeebe:input source="https://ont-1.tasklist.camunda.io/5e85b607-159b-443f-a87a-24ab8b90aacb/v1/tasks/search" target="url" />
          <zeebe:input source="={}" target="headers" />
          <zeebe:input source="https://login.cloud.camunda.io/oauth/token" target="authentication.oauthTokenEndpoint" />
          <zeebe:input source="client_id_xxx" target="authentication.clientId" />
          <zeebe:input source="client_secret_xxx" target="authentication.clientSecret" />
          <zeebe:input source="tasklist.camunda.io" target="authentication.audience" />
          <zeebe:input source="credentialsBody" target="authentication.clientAuthentication" />
          <zeebe:input source="20" target="connectionTimeoutInSeconds" />
        </zeebe:ioMapping>
        <zeebe:taskHeaders />
      </bpmn:extensionElements>
      <bpmn:incoming>Flow_1rfjn0u</bpmn:incoming>
      <bpmn:outgoing>Flow_0644q48</bpmn:outgoing>
    </bpmn:serviceTask>
    <bpmn:manualTask id="Activity_0xr2bie" name="Microsoft Dataverse">
      <bpmn:incoming>Flow_0644q48</bpmn:incoming>
      <bpmn:outgoing>Flow_1u5knz4</bpmn:outgoing>
    </bpmn:manualTask>
    <bpmn:sequenceFlow id="Flow_1rfjn0u" sourceRef="Gateway_1728wpj" targetRef="Activity_14w6jo5" />
    <bpmn:parallelGateway id="Gateway_1728wpj">
      <bpmn:incoming>Flow_0pt0f73</bpmn:incoming>
      <bpmn:outgoing>Flow_1rfjn0u</bpmn:outgoing>
      <bpmn:outgoing>Flow_08nf2l9</bpmn:outgoing>
    </bpmn:parallelGateway>
    <bpmn:sequenceFlow id="Flow_08nf2l9" sourceRef="Gateway_1728wpj" targetRef="Activity_0tyc8ls" />
    <bpmn:userTask id="Activity_0tyc8ls" name="Comment Form">
      <bpmn:extensionElements>
        <zeebe:formDefinition formKey="camunda-forms:bpmn:userTaskForm_1hjkdi0" />
      </bpmn:extensionElements>
      <bpmn:incoming>Flow_08nf2l9</bpmn:incoming>
      <bpmn:outgoing>Flow_1bjqhji</bpmn:outgoing>
    </bpmn:userTask>
    <bpmn:sequenceFlow id="Flow_1bjqhji" sourceRef="Activity_0tyc8ls" targetRef="Gateway_00g9ib4" />
    <bpmn:sequenceFlow id="Flow_16iax1n" sourceRef="Gateway_00g9ib4" targetRef="Event_1nq7pa3" />
    <bpmn:parallelGateway id="Gateway_00g9ib4">
      <bpmn:incoming>Flow_1u5knz4</bpmn:incoming>
      <bpmn:incoming>Flow_1bjqhji</bpmn:incoming>
      <bpmn:outgoing>Flow_16iax1n</bpmn:outgoing>
    </bpmn:parallelGateway>
  </bpmn:process>
  <bpmndi:BPMNDiagram id="BPMNDiagram_1">
    <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="Process_01oeys7">
      <bpmndi:BPMNShape id="_BPMNShape_StartEvent_2" bpmnElement="StartEvent_1">
        <dc:Bounds x="150" y="100" width="36" height="36" />
        <bpmndi:BPMNLabel>
          <dc:Bounds x="156" y="143" width="24" height="14" />
        </bpmndi:BPMNLabel>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Activity_1srfhr8_di" bpmnElement="Activity_14w6jo5">
        <dc:Bounds x="310" y="78" width="100" height="80" />
        <bpmndi:BPMNLabel />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Activity_1lhp101_di" bpmnElement="Activity_0xr2bie">
        <dc:Bounds x="460" y="78" width="100" height="80" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Gateway_1o9a92a_di" bpmnElement="Gateway_1728wpj">
        <dc:Bounds x="225" y="93" width="50" height="50" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Activity_0vu7mjj_di" bpmnElement="Activity_0tyc8ls">
        <dc:Bounds x="310" y="190" width="100" height="80" />
        <bpmndi:BPMNLabel />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Event_1nq7pa3_di" bpmnElement="Event_1nq7pa3">
        <dc:Bounds x="712" y="100" width="36" height="36" />
        <bpmndi:BPMNLabel>
          <dc:Bounds x="720" y="76" width="20" height="14" />
        </bpmndi:BPMNLabel>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Gateway_0uzpeau_di" bpmnElement="Gateway_00g9ib4">
        <dc:Bounds x="615" y="93" width="50" height="50" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge id="Flow_0pt0f73_di" bpmnElement="Flow_0pt0f73">
        <di:waypoint x="186" y="118" />
        <di:waypoint x="225" y="118" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_1u5knz4_di" bpmnElement="Flow_1u5knz4">
        <di:waypoint x="560" y="118" />
        <di:waypoint x="615" y="118" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_0644q48_di" bpmnElement="Flow_0644q48">
        <di:waypoint x="410" y="118" />
        <di:waypoint x="460" y="118" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_1rfjn0u_di" bpmnElement="Flow_1rfjn0u">
        <di:waypoint x="275" y="118" />
        <di:waypoint x="310" y="118" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_08nf2l9_di" bpmnElement="Flow_08nf2l9">
        <di:waypoint x="250" y="143" />
        <di:waypoint x="250" y="230" />
        <di:waypoint x="310" y="230" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_1bjqhji_di" bpmnElement="Flow_1bjqhji">
        <di:waypoint x="410" y="230" />
        <di:waypoint x="640" y="230" />
        <di:waypoint x="640" y="143" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_16iax1n_di" bpmnElement="Flow_16iax1n">
        <di:waypoint x="665" y="118" />
        <di:waypoint x="712" y="118" />
      </bpmndi:BPMNEdge>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</bpmn:definitions>
```

**Comment by upgradingdave** [comment]
Sorry, please disregard! This was because of some stale debug code I had been experimenting with!
